default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: PUBLIC
      database: DBT_TARGET
      warehouse: DEMO_WH
      schema: SBX
      threads: 1
      client_session_keep_alive: False
